### PR TITLE
prevent extras from going apeshit

### PR DESCRIPTION
**Pull request by Apmunute**
Something went wrong while saving the prefix. Please check console.

### CODE REVIEW

**Comment by business-goose** [comment]
please merge this... extras is retarded, i want to play on kaboom :sob:

**Comment by Apmunute** [comment]
> please merge this... extras is retarded, i want to play on kaboom sob

This doesn't happen on kaboom, but it may happen on kaboom clones

**Comment by mathiascode** [comment]
What exactly is this change trying to fix?

**Comment by Apmunute** [comment]
> What exactly is this change trying to fix?

sometimes extras doesn't generate the "Extras" folder and it can't create it. with this i automatically create the folder and give it correct permissions

**Comment by mathiascode** [comment]
What is the error printed in the console? This kind of band-aid fix should not be necessary.

**Comment by Apmunute** [comment]
> What is the error printed in the console? This kind of band-aid fix should not be necessary.

I haven't looked into the error printed, but it is probably something related to missing permissions to create a folder. It's not a band-aid fix, it's a fix.

**Comment by business-goose** [comment]
works on my machine:tm:

**Comment by mathiascode** [comment]
Thanks, I see what's going on. The official server has the Extras plugin folder in the reset folder, while the GitHub repo lacks it. I'll push it in a sec.

**Comment by mathiascode** [comment]
Addressed in https://github.com/kaboomserver/server/commit/2649ff90b271c546d25665b45bfb42549fcee30c.

**Pull request closed without merging**
